# Aula 06 - Exercício 05

### Alunos:
 - 
 - 

## Multilayer Perceptron para classificação do dataset Wine
Neste exercício utilizaremos a base de dados Wine, que consiste em 178 exemplos de dimensionalidade 13, separados em 3 classes. Os atributos dessa base de dados não estão normalizados, apresentando intervalos variados de valores.

- Carregue a base de dados wine e normalize entre 0 e 1 o valor dos seus atributos

In [1]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.preprocessing import MinMaxScaler

x, y = load_wine(return_X_y=True)
scaler = MinMaxScaler()
print(x)
print(np.max(x))
print(np.min(x))
scaler.fit(x)
x = scaler.transform(x)
print(x)
print(np.max(x))
print(np.min(x))
print(y)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
1680.0
0.13
[[0.84210526 0.1916996  0.57219251 ... 0.45528455 0.97069597 0.56134094]
 [0.57105263 0.2055336  0.4171123  ... 0.46341463 0.78021978 0.55064194]
 [0.56052632 0.3201581  0.70053476 ... 0.44715447 0.6959707  0.64693295]
 ...
 [0.58947368 0.69960474 0.48128342 ... 0.08943089 0.10622711 0.39728959]
 [0.56315789 0.36561265 0.54010695 ... 0.09756098 0.12820513 0.40085592]
 [0.81578947 0.66403162 0.73796791 ... 0.10569106 0.12087912 0.20114123]]
1.0
0.0
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 

---
- Agora divida a base em conjunto de teste e treino. Utilize 20% da base para teste e 80% para treino.

In [0]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.20,random_state=1, stratify=y)
# x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.20,random_state=1)



### Comentário
Embora eu não tenha pedido no exercício, é interessante utilizar o parâmetro stratify. O classificador apresenta um resultado muito mais próximo do esperado se utilizarmos um conjunto estratificado (proporção das classes do conjunto original se mantém nos conjuntos de treino e teste). 

Lembro que algumas pessoas em sala reportaram uma acurácia de 100% no conjunto de teste. O que pode ter acontecido é que uma classe mais "fácil" de ser classificada foi favorecida na hora de dividir os conjuntos, levando o classificador a errar menos.

---
- Treine 3 classificadores MLP (com `solver='sgd'`), variando o número de neurônios na camada escondida. Reporte o score dos classificadores nos conjuntos de treino e teste.

In [44]:
from sklearn.neural_network import MLPClassifier

sizes = [2, 5, 10]
mlps = []
for i in range(0, 3):
  mlps.append(MLPClassifier(hidden_layer_sizes=(sizes[i],), max_iter=200,
                      solver='sgd', tol=1e-3, random_state=1,
                      learning_rate_init=.1))

  mlps[i].fit(x_train, y_train)
  print("Training set score: %f" % mlps[i].score(x_train, y_train))
  print("Test set score: %f" % mlps[i].score(x_test, y_test))
  
best = 1
worst = 0

Training set score: 0.401408
Test set score: 0.388889
Training set score: 1.000000
Test set score: 0.972222
Training set score: 0.992958
Test set score: 0.972222


---
- Selecione uma amostra de tamanho 10 do conjunto de testes. Selecione o classificador que apresentou maior acurácia no conjunto de testes e calcule, para cada elemento da amostra, a classe esperada, a classe obtida e a probabilidade estimada de cada classe

In [45]:
samples = x_test[10:20]
samples_t = y_test[10:20]

pred_proba = mlps[best].predict_proba(samples)
pred = mlps[best].predict(samples)

i = 0
for prob in pred_proba:
  print("Amostra %d:" % i)
  print("Esperado %s, obtido %s" % (samples_t[i], pred[i]))
  print(prob.round(2))
  i += 1


Amostra 0:
Esperado 0, obtido 0
[1. 0. 0.]
Amostra 1:
Esperado 1, obtido 1
[0.32 0.66 0.02]
Amostra 2:
Esperado 1, obtido 1
[0.02 0.97 0.01]
Amostra 3:
Esperado 2, obtido 2
[0.01 0.06 0.93]
Amostra 4:
Esperado 1, obtido 1
[0. 1. 0.]
Amostra 5:
Esperado 1, obtido 1
[0.01 0.99 0.  ]
Amostra 6:
Esperado 1, obtido 1
[0. 1. 0.]
Amostra 7:
Esperado 0, obtido 0
[1. 0. 0.]
Amostra 8:
Esperado 0, obtido 0
[1. 0. 0.]
Amostra 9:
Esperado 0, obtido 0
[1. 0. 0.]


---
- Agora sobre a mesma amostra escolhida anteriormente, selecione o classificador que apresentou menor acurácia no conjunto de testes e calcule, para cada elemento da amostra, a classe esperada, a classe obtida e a probabilidade esperada de cada classe.

In [46]:
pred_proba = mlps[worst].predict_proba(samples)
pred = mlps[worst].predict(samples)

i = 0
for prob in pred_proba:
  print("Amostra %d:" % i)
  print("Esperado %s, obtido %s" % (samples_t[i], pred[i]))
  print(prob.round(2))
  i += 1

Amostra 0:
Esperado 0, obtido 1
[0.31 0.45 0.24]
Amostra 1:
Esperado 1, obtido 1
[0.31 0.45 0.24]
Amostra 2:
Esperado 1, obtido 1
[0.31 0.45 0.24]
Amostra 3:
Esperado 2, obtido 1
[0.31 0.45 0.24]
Amostra 4:
Esperado 1, obtido 1
[0.31 0.45 0.24]
Amostra 5:
Esperado 1, obtido 1
[0.31 0.45 0.24]
Amostra 6:
Esperado 1, obtido 1
[0.31 0.45 0.24]
Amostra 7:
Esperado 0, obtido 1
[0.31 0.45 0.24]
Amostra 8:
Esperado 0, obtido 1
[0.31 0.45 0.24]
Amostra 9:
Esperado 0, obtido 1
[0.31 0.45 0.24]




---

- Faça uma análise das probabilidades calculadas por cada classificador nos exemplos corretos e relacione-as com a 'qualidade' dos mesmos.

O classificador que apresenta 'qualidade' mais alta apresenta maior probabilidade nas classes esperadas, quando comparado ao outro. Por exemplo, embora a amostra 2 tenha sido classificada corretamente nos dois classificadores, o primeiro classificador apresentou uma confiança muito maior que o segundo.

---
- Calcule, usando 10-fold cross-validation, a acurácia média da melhor configuração de classificador que você utilizou e seu desvio padrão

In [48]:
from sklearn.model_selection import StratifiedKFold
scores = []
skf = StratifiedKFold(n_splits=10)
for train_index, test_index in skf.split(x, y):
  x_train, x_test = x[train_index], x[test_index]
  y_train, y_test = y[train_index], y[test_index]
  mlp = MLPClassifier(hidden_layer_sizes=(5,), max_iter=200,
                      solver='sgd', tol=1e-3, random_state=1,
                      learning_rate_init=.1)

  mlp.fit(x_train, y_train)  
  scores.append(mlp.score(x_test, y_test))
print(scores)
scores = np.asarray(scores)
print(np.mean(scores))
print(np.std(scores))

[1.0, 0.9444444444444444, 1.0, 0.9444444444444444, 0.9444444444444444, 1.0, 1.0, 1.0, 1.0, 1.0]
0.9833333333333334
0.02545875386086579
